export const tabBgColor = '#f8f7f7'
export const activeTintColor = '#007aff'
export const inActiveTintColor = '#a1a1a1'
export const chatHeaderBgColor = '#f8f7f7'
export const chatBodyColor = '#ffffff'